name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'  
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv venv
          uv pip install -r docs-requirements.txt
      
      - name: Clean build directory
        run: |
          uv run sphinx-build -M clean ./source ./build
           
      - name: Sphinx build
        run: |
          uv run sphinx-build ./source ./build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/
          force_orphan: true