[project]
name = "delta-enigma-docs"
version = "0.1.0"
description = "Delta Enigma Data Management Guidelines"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "myst-parser>=4.0.0",
    "ruff>=0.7.2",
    "sphinx-book-theme>=1.1.3",
    "sphinx>=8.1.3",
]
